- Crm/PersonAttributeForms.ascx
- Crm/PersonAttributeForms.ascx.cs
Fixes problem with canceling new items and saving existing items.
---------
KFS
---------
---------
* `Crm/PersonAttributeForms.ascx`
* `Crm/PersonAttributeForms.ascx.cs`
---------
No
> Advanced Person Attribute Form Cancel Item Bug

- Fundraising/FundraisingParticipant.ascx
- Fundraising/FundraisingParticipant.ascx.cs
Bring Fundraising Participant block up to parity with v9 changes.
---------
* Bring Fundraising Participant block up to parity with v9 changes.
---------
Kensington
---------
No
---------
- Fundraising/FundraisingParticipant.ascx
- Fundraising/FundraisingParticipant.ascx.cs
---------
No
> Fundraising Participant v9

- CheckIn/Manager/Locations.ascx.cs
Comment out ZPL print button capability as it does not work yet. If anyone wants it we will need someone to fund working on it.
---------
Comment out ZPL print button capability as it does not work.
---------
Warranty
---------
No more setting.
---------
CheckIn/Manager/Locations.ascx.cs
---------
No
> Check-in Manager ZPL Print Button

- Fundraising/FundraisingProgress.ascx.cs
Fixed if new group type that inherits Fundraising Opportunity is used it will also be allowed.
---------
- Fixed if new group type that inherits Fundraising Opportunity is used it will also be allowed.
---------
Cedar Creek
---------
No
---------
Fundraising/FundraisingProgress.ascx.cs
---------
No
> Fundraising progress Inherited Group Type

- Eventbrite/EventbriteSettings.ascx.cs
Fix for Eventbrite block for a potential SelectedValue error if changing token.
---------
- Fixed Eventbrite block SelectedValue error if changing token.
---------
Warranty
---------
No
---------
Eventbrite/EventbriteSettings.ascx.cs
---------
No
> Eventbrite Minor Fix

- Event/RegistrantDetail.ascx.cs
- Event/RegistrationEntry.ascx.cs
- Event/RegistrationInstanceDetail.ascx.cs
- Finance/ShelbyGLExport.ascx.cs
**Thank you for your code contribution, we will take your code suggestion into consideration. It will be reviewed, and based on code quality and need addressed, we will determine acceptance. If this code addresses a feature request or issue, be sure to link to that issue.** 
11.3 Updates.  Also, take note of Daniel's issue with a core block that has to manually be deleted after upgrading: https://github.com/SparkDevNetwork/Rock/issues/4310
---------
Updated Registration and Shelby Export blocks for v11 compatiblity.
---------
* Event/RegistrantDetail.ascx.cs
* Event/RegistrationEntry.ascx.cs
* Event/RegistrationInstanceDetail.ascx.cs
* Finance/ShelbyGLExport.ascx.cs
---------
Possibly.  I think most of these changes will be v10 compatible, but it's possible there could be some v11 only …
> Changes for v11.3 to build and run.

- CheckIn/AttendanceReports/AttendanceReportSample.html
Fixes the lava in the sample attendance report.
---------
Fixes the default Attendance Report lava.  Reminder, this lava file needs to be manually updated in it's Merge Template.
---------
* CheckIn/AttendanceReports/AttendanceReportSample.html
---------
No
> Use the subrow for the additional report items.

- CheckIn/AttendanceReport.ascx
- CheckIn/AttendanceReport.ascx.cs
Changed the attendance report filters so that multiple areas can be reported at the same time.
---------
Changed the attendance report filters so that multiple areas can be reported at the same time.
---------
---------
* CheckIn/AttendanceReport.ascx
* CheckIn/AttendanceReport.ascx.cs
---------
No
> Change filter layout

- Core/DefinedValueList.ascx
- Core/DefinedValueList.ascx.cs
Create a derivative block of the defined values list with filter controls.
---------
- Added new block for defined values list with filter controls.
---------
New Hope
---------
---------
- Core/DefinedValueList.ascx
- Core/DefinedValueList.ascx.cs
---------
No
> Defined Values List with Filter

- Core/DefinedValueList.ascx
- Core/DefinedValueList.ascx.cs
Change active checkbox filter to a dropdown, so you can see all, active or inactive.
---------
Change active checkbox filter to a dropdown, so you can see all, active or inactive.
---------
Warranty/New Hope
---------
---------
- Core/DefinedValueList.ascx
- Core/DefinedValueList.ascx.cs
---------
No
> Defined Value List Filter Active Dropdown

- Groups/GroupDetailLava.ascx
- Groups/GroupDetailLava.ascx.cs
Added support for custom Group schedules.
none
---------
* Added support for custom Group schedules.
---------
Lifegate Church
---------
---------
* Groups/GroupDetailLava.ascx
* Groups/GroupDetailLava.ascx.cs
---------
none
> Custom Schedule Support In Group Details Lava

- Eventbrite/EventbriteSettings.ascx.cs
Eventbrite API Change update for description field being removed and summary being added.
---------
Eventbrite API Change update for description field being removed and summary being added.
---------
Kensington
---------
No
---------
Eventbrite/EventbriteSettings.ascx.cs
---------
Yes, requires updated DLL from https://github.com/KingdomFirst/RockAssemblies/pull/32
> Eventbrite API Change

- Cms/PublicProfileEdit.ascx
- Cms/PublicProfileEdit.ascx.cs
Bring our KFS copy of Public Profile Edit back to par with 12.3. Includes person impersonation still, which is unique to our version of the block.
---------
- Updated KFS Public Profile Edit to v12.3 changes.
---------
OHC
---------
---------
- Cms/PublicProfileEdit.ascx
- Cms/PublicProfileEdit.ascx.cs
---------
No
> KFS Public Profile Edit - Reinitialize with v12 version

- Vimeo/ReadMe.md
**Thank you for your code contribution, we will take your code suggestion into consideration. It will be reviewed, and based on code quality and need addressed, we will determine acceptance. If this code addresses a feature request or issue, be sure to link to that issue.** 
Created/Updated Vimeo ReadMe.md from Rock shop documentation.
---------
- Added Rock shop Readme to Repo
---------
Support
---------
No
---------
Vimeo/ReadMe.md
---------
No
> Vimeo ReadMe.md

- Intacct/ReadMe.md
Intacct ReadMe.md
Created/Updated Intacct ReadMe.md from Rock shop documentation
---------
- Created/Updated Intacct ReadMe.md from Rock shop documentation
---------
Support
---------
No
---------
Intacct/ReadMe.md
---------
No
> Intacct ReadMe.md

- CheckIn/Manager/ReadMe.md
Created/Updated Advanced Check-In Monitor ReadMe.md from Rock shop documentation.
---------
Created/Updated Advanced Check-In Monitor ReadMe.md from Rock shop documentation.
---------
Support
---------
No
---------
CheckIn/Manager/ReadMe.md
---------
No
> Advanced Check-In Monitor ReadMe.md

- CheckIn/Manager/Locations.ascx.cs
Added/updated code to match v12 Live Metrics block for Group Type cookie checking.
---------
- Fixed an issue with our Check-in Manager not loading the check-in area selected via the new "Settings" section of Check-in manager in v12.
---------
Fellowship Greenville
---------
No
---------
- CheckIn/Manager/Locations.ascx.cs
---------
No
> Check-in Manager Update

- Fundraising/FundraisingProgress_ReadMe.md
Updated/Modified Fundraising Progress ReadMe.md from Rock Shop Documentation.
---------
Updated/Modified Fundraising Progress ReadMe.md from Rock Shop Documentation.
---------
Support
---------
No
---------
Fundraising/FundraisingProgress_ReadMe.md
---------
No
> Update Fundraising Progress ReadMe.md

- Groups/GroupFinder.ascx
- Groups/GroupFinder.ascx.cs
- Vimeo/ContentChannelItemVimeoSync.ascx.cs
A few tweaks to Group finder for some possible layout issues when filters were turned off. Updated a setting to have a Tri-State instead of just True/False. 
Added the search and clear buttons to the hide initial filters list to support an additional group finder layout.
Updated wording on collapse settings.
Also decided to fix #18 when I couldn't get it to work locally. 
**Collapse Filters on Search** - When set to yes, all filters will be collapsed into a single 'Filters' dropdown.
New Values: No, Yes, Same as Initial Load
---------
- A few minor bug fixes for Group Finder
- Updated "Collapse Filters on Search" to a tri-state setting, No, Yes or Same as Initial Load.
- Added the search and clear buttons to the hide initial filters list to support an additional group …
> Group Finder Updates

- Intacct/BatchToJournal.ascx
- Intacct/BatchToJournal.ascx.cs
Enhanced KFS Intacct Batch to Journal plugin to now allow optional creation of Other Receipts in Intacct for Rock batches instead of journal entries. A couple new block settings have been added to enable and configure this new functionality. When properly configured, the plugin will request all required information from the user to create a valid Other Receipt in the Intacct account. When the export button is clicked, everything behaves the same as it does in journal entry mode other than resulting in an other receipt in Intacct rather than a journal entry. Once the other receipt is created, the Intacct software will automatically create a "CR" type journal entry for the receipt.
* Export Mode - Determines the type of object to create in Intacct ( "JournalEntry" or …
> Add Other Receipt capabilities to Intacct Batch to Journal plugin

- StepsToCare/CareDashboard.ascx
- StepsToCare/CareDashboard.ascx.cs
- StepsToCare/CareEntry.ascx
- StepsToCare/CareEntry.ascx.cs
- Added ability to flag Need's as "Workers Only".
- Added additional security permissions for "View All" and "Care Workers".
- Added Notification preferences to the Care Dashboard.
- Added logic to Care Entry to be able to handle new notification preferences.
- Fixes #83 
Security Permissions
---------
- Added ability to flag Need's as "Workers Only".
- Added additional security permissions for "View All" and "Care Workers".
- Added Notification preferences to the Care Dashboard.
---------
Rock Springs
---------
---------
- StepsToCare/CareEntry.ascx
- StepsToCare/CareEntry.ascx.cs
---------
Steps to Care now requires 12.4 due to an added GetAttributeValue method I am using to bypass looking up an …
> Steps to Care - Security Permissions and Notification Preferences

- Crm/PersonAttributeForms.ascx.cs
Added support for Anniversary Date and Middle Name person fields.
---------
* Added support for Anniversary Date and Middle Name person fields.  
* Changed Person Field dropdown items to display in alphabetical order.
---------
Lifegate Church
---------
---------
* Crm/PersonAttributeForms.ascx.cs
---------
none
> F: Person Attributes Forms Advanced - Add Anniversary Date and Middle Name

- StepsToCare/CareDashboard.ascx
Let's not replace a number that could be in other parts of the string when we should be specific.
---------
Minor bug fix with person popover content
---------
RSC
---------
No
---------
StepsToCare/CareDashboard.ascx
---------
No
> Bug fix for Steps to Care

- HelloWorld.txt
- Zoom/Webhook.ashx
- Zoom/ZoomSettings.ascx
- Zoom/ZoomSettings.ascx.cs
New Zoom Room integration with BEMA's Room Reservation plugin. Connect Locations to existing Zoom Rooms in your church's Zoom Room account and Zoom meetings will be created whenever a new Reservation is created in the Room Reservations plugin.
All new blocks and settings!  
---------
* Released Zoom Room integration plugin.
---------
Oak Hills Church
---------
New Reservation entity attribute ( created by migration ):
New Zoom Rooms Defined Type ( created by migration ):  
Zoom Settings block ( edit mode ):  
Zoom Settings Block ( view mode ):
Zoom Settings Page ( with Zoom Rooms synced ):  
Set Zoom Meeting defined type attributes:  
New Zoom Room Reservation Scheduling and Maintenance job:  
New Zoom Meeting Group Reminder job:  
---------
[Add a file list here] …
> WIP: ZoomRoom Integration

- Crm/PersonAttributeForms.ascx.cs
- Groups/GroupFinder.ascx
- Groups/GroupFinder.ascx.cs
- Intacct/BatchToJournal.ascx.cs
- Prayer/PrayerWall.ascx.cs
- StepsToCare/CareDashboard.ascx.cs
Packages ready for v13 with these changes.
---------
- v13 Support Added for our blocks. Specifically, Person Attributes Advanced, Group Finder, Prayer Wall and Steps to Care.
- Added Campus types and Campus statuses as options to Group Finder.
---------
Warranty
---------
New settings added to Group Finder
---------
- Crm/PersonAttributeForms.ascx.cs
- Intacct/BatchToJournal.ascx.cs
- Prayer/PrayerWall.ascx.cs
---------
Group Finder and Prayer Wall have v13 specific changes, they will no longer be compatible with v12 and below from the repo once this is merged.
> v13 Changes

- Crm/PersonAttributeForms_Readme.md
- Eventbrite/ReadMe.md
- FinancialEdge/ReadMe.md
- Groups/GroupFinder_Readme.md
- Intacct/ReadMe.md
- ShelbyFinancials/ReadMe.md
- Vimeo/ReadMe.md
readme file updates for v13 supported plugins
---------
reame file updates
---------
KFS
---------
none
---------
* Crm/PersonAttributeForms_Readme.md
* Eventbrite/ReadMe.md
* FinancialEdge/ReadMe.md
* Groups/GroupFinder_Readme.md
* Intacct/ReadMe.md
* ShelbyFinancials/ReadMe.md
* Vimeo/ReadMe.md
---------
none
> Plugin readme file updates for v13

- Zoom/Webhook.ashx
- Zoom/ZoomSettings.ascx.cs
(cherry picked from commit 4bea2496cd99705d52342e24affe49ab18c348d3)
> Cherry Pick into Hotfix-12 - Merge pull request #94 from KingdomFirst/gm-propogateChangesFromAssembly

- StepsToCare/CareDashboard.ascx
- StepsToCare/CareDashboard.ascx.cs
- StepsToCare/CareEntry.ascx
- StepsToCare/CareEntry.ascx.cs
- StepsToCare/CareWorkers.ascx
- StepsToCare/CareWorkers.ascx.cs
(Cherry pick from https://github.com/KingdomFirst/RockBlocks/commit/20597e2452a445fe0c612ab5c63b9a450403c216)
> Cherry Pick into Hotfix-12 - Merge pull request #95 from KingdomFirst/feature/nbh-StepsToCareSubNeeds

- StepsToCare/CareDashboard.ascx.cs
Add new setting to Dashboard for Complete Child Needs on Parent Completion
- _Complete Child Needs on Parent Completion_
---------
Add new setting to Dashboard for Complete Child Needs on Parent Completion
---------
RSC
---------
---------
StepsToCare/CareDashboard.ascx.cs
---------
No, though there is an assembly update for block attribute and default attribute value. https://github.com/KingdomFirst/RockAssemblies/pull/68
> Steps to Care Sub Needs New Setting

- Groups/GroupFinder.ascx.cs
- Prayer/PrayerWall.ascx.cs
Revert v13 specific block changes for lava
---------
Revert v13 specific block changes for lava
---------
Warranty
---------
no
---------
- Prayer/PrayerWall.ascx.cs
---------
No
> Revert v13 specific block changes

- StepsToCare/CareDashboard.ascx.cs
Though it should not be possible, add a fix for if the category is null somehow.
---------
- Fixed potential issue when Category is null.
---------
Warranty
---------
No
---------
StepsToCare/CareDashboard.ascx.cs
---------
No
> Steps to Care Null Category Fix

- Groups/GroupFinder_Readme.md
Group Finder Documentation Update to describe how to use url parameters.
---------
Group Finder Documentation Update
---------
Warranty
---------
See rich diff of document, or full document, end portion: https://github.com/KingdomFirst/RockBlocks/blob/beabcc974b80d1b82f0a2c59f0936da22e65a38b/Groups/GroupFinder_Readme.md
---------
Groups/GroupFinder_Readme.md
---------
no
> Group Finder Documentation Update

- Crm/BusinessBio.ascx
- Crm/BusinessBio.ascx.cs
- Crm/EditBusiness.ascx
- Crm/EditBusiness.ascx.cs
- Finance/BusinessDetail.ascx
- Finance/BusinessDetail.ascx.cs
Bring Person Bio block into repo and convert to specific for businesses. Removing elements that are unnecessary for businesses. Also found I needed to pull in Person Edit and Business Detail blocks. Person Edit got changed into a "Business Edit" block, which again, removed unnecessary fields, like Gender, Marital Status, etc. Matching business detail edit capabilities, but keeping some that they wanted, such as business photos. Added a new setting to Business Detail block to be able to hide the details section, so that the block could be used to just list Business Contacts on its own.
---------
- Added new Business Bio Block, removing unnecessary fields for businesses.
- Added new Business Edit Block, removing unnecessary fields for businesses.
- Added a modified Business Detail block …
> Business Bio Blocks

- Webhooks/Edify.ashx
- Webhooks/PostalServer.ashx
Create Edify webhook for open and link tracking for communications.
---------
- Create Edify webhook for open and link tracking for communications.
---------
Edify
---------
---------
Webhooks/Edify.ashx
---------
No
> Edify Webhook

- Webhooks/Edify.ashx
Added logging and first attempt at optimizing requests based on analysis of processing time for each webhook request.
---------
- Added code to help Rock servers from getting overwhelmed by webhook requests.
---------
Warranty
---------
No
---------
Webhooks/Edify.ashx
---------
No
> Edify Webhook Delay

- Intacct/BatchToJournal.ascx.cs
- Intacct/BatchesToJournal.ascx.cs
- Added a warning dialog if Intacct responds poorly to our request, i.e. our settings or data are bad.
---------
- Added a warning dialog if Intacct responds poorly to our request, i.e. our settings or data are bad.
---------
Warranty
---------
---------
- Intacct/BatchToJournal.ascx.cs
- Intacct/BatchesToJournal.ascx.cs
---------
No
> Intacct Warning on Error

- Intacct/BatchToJournal.ascx
- Intacct/BatchToJournal.ascx.cs
Address reported bug on Batch to Intacct 
None
---------
* Addressed bug discovered in the batch to intacct export
* 
---------
KFS
---------
N/A
---------
* Intacct/BatchToJournal.ascx - added the dialog control
* Intacct/BatchToJournal.ascx.cs - added the using needed for the dialog control
---------
None
> Fix mising alert diaglog in the ascx

- Groups/GroupFinder.ascx.cs
- Prayer/PrayerWall.ascx.cs
- Enabled proper Fluid support within Group Finder and Prayer Wall
---------
- Enabled proper Fluid support within Group Finder and Prayer Wall
---------
Warranty
---------
Nothing to see, just possible less errors. 
---------
- Prayer/PrayerWall.ascx.cs
---------
No
> Group Finder and Prayer Wall v13 Changes

- StepsToCare/CareDashboard.ascx.cs
Steps to Care bug fix for Benevolence Request action. Internal server error due to Benevolence type not being set in v13+.
_Benevolence Type_, The Benevolence type used when creating benevolence requests from Steps to Care 'Actions'
---------
- Fixed an issue when using the "Add Benevolence Request" action the Care Need dashboard.
---------
Warranty
---------
---------
StepsToCare/CareDashboard.ascx.cs
---------
Rock v13+ only.
> Steps to Care bug fix

- Groups/GroupFinder.ascx.cs
Update group finder to check for null campus controls before setting page param value
---------
- Fixed null reference exception when using filter_Campus url parameter.
---------
Warranty
---------
No
---------
---------
No
> Group Finder Bug Fix

- StepsToCare/CareDashboard.ascx.cs
- Fixed minor issue with default lava template.
- Fixed TouchCount in tooltip for non-recurring touches.
---------
- Fixed minor issue with default lava template.
- Fixed TouchCount in tooltip for non-recurring touches.
---------
CBCN/Warranty
---------
No
---------
StepsToCare/CareDashboard.ascx.cs
---------
No
> Steps to Care Minor Bug

- Groups/GroupAttendanceMulti.ascx.cs
Update so person picker opens after selected a group.
---------
- Update so person picker opens after selected a group
---------
Ada
---------
No
---------
Groups/GroupAttendanceMulti.ascx.cs
---------
No
> Multi Group Attendance

- Cms/ProfileBioEdit.ascx
- Cms/ProfileBioEdit.ascx.cs
New and improved Edit Profile block. Fully customizable with sortable panels, fields and more. Includes ability to create new Family Members and edit existing family members all from the same interface.
---------
New and improved Edit Profile block.
---------
VC
---------
Example settings customized:   
Default settings:   
---------
Cms/ProfileBioEdit.ascx
Cms/ProfileBioEdit.ascx.cs
---------
No
> Flexible Edit Profile Block

- Cms/ProfileBioEdit.ascx
- Cms/ProfileBioEdit.ascx.cs
Noticed spacing was off between panel fields. Should have had a row to negate column padding. Also a few other random small updates.
---------
Noticed spacing was off between panel fields. Should have had a row to negate column padding. Also a few other random small updates.
---------
VWC
---------
No
---------
- Cms/ProfileBioEdit.ascx
- Cms/ProfileBioEdit.ascx.cs
---------
No
> Edit Profile Bio Updates
