- ShelbyFinancials/BatchToJournal.ascx
- ShelbyFinancials/BatchToJournal.ascx.cs
- ShelbyFinancials/BatchesToJournal.ascx
- ShelbyFinancials/BatchesToJournal.ascx.cs
Enable lava support for the Journal Description column. Specifically with the request of wanting to include Registration information in the description.
- Journal Description Lava - Lava for the journal description column per line. Default: Batch.Id: Batch.Name
- Enable Debug - Outputs the object graph to help create your Lava syntax
---------
**Shelby Financials**
- Added lava support for the Journal Description Column
---------
FPG
---------
---------
- ShelbyFinancials/BatchToJournal.ascx
- ShelbyFinancials/BatchToJournal.ascx.cs
- ShelbyFinancials/BatchesToJournal.ascx
- ShelbyFinancials/BatchesToJournal.ascx.cs
---------
Yes, requires DLL/Assembly update. https://github.com/KingdomFirst/RockAssemblies/pull/6
> Shelby Financials lava update

- Intacct/BatchToJournal.ascx
- Intacct/BatchToJournal.ascx.cs
Added support for a lava customization memo field per line item on export. Including an "Enable Debug" feature to show the available fields on export. (Including it adds something to the memo line in general, prior to this version it was blank).
- `Journal Memo Lava`: adds the ability to customize what information you have per line in the export (Default: Batch.Id: Batch.Name)
- `Enable Debug` outputs the object graph after export to help create your lava syntax.
---------
- Added data to memo column of export and gave it the ability to be customized via lava in the block settings.
---------
OHC
---------
[Add a screenshot here]
---------
- Intacct/BatchToJournal.ascx
- Intacct/BatchToJournal.ascx.cs
---------
Requires assembly update in …
> Intacct Lava Memo Field

- Groups/GroupFinder.ascx
- Groups/GroupFinder.ascx.cs
+ Added ability to have a custom sort based on an attribute filter in Group Finder. If you have a multi-select attribute or a multi-select defined type it will sort the results based on if multiple options match as the first results. For example, Marriage and Kid Friendly are selected to filter by. Groups with both Marriage and Kid Friendly will show up higher in results then groups with just Marriage or just Kid Friendly tags.
+ Added FilterValues lava object to be able to know what was searched for in the lava.
*Attribute Custom Sort*: Select an attribute to sort by if a group contains multiple of the selected filter options.
---------
- Added ability to have a multi-select custom sort option with a selected attribute.
---------
Kensington
---------
Before change (or …
> Group Finder Custom Attribute Sort

- Fundraising/FundraisingProgress.ascx
- Fundraising/FundraisingProgress.ascx.cs
Found a discrepancy of our block on a clients server that needed to be pulled in to our repo. Total Amount raised option was not in our code. You can have it show as a progress bar or a single number with this setting.
*Show Total Amount Raised* added.
---------
- Show Total Amount Raised added as an option to our block and fixed to properly show decimals.
---------
Kensington
---------
*Customized for client:*
---------
- Fundraising/FundraisingProgress.ascx
- Fundraising/FundraisingProgress.ascx.cs
---------
No
> Fundraising progress Update

- Groups/GroupFinder.ascx.cs
Null reference exception fixes when using Postal Code option.
---------
- Fixed a null reference exception when the current logged in user doesn't have an address.
- Fixed a potential null reference exception from postal code search.
---------
Venture
---------
No
---------
---------
No
> Group Finder Null Reference Exceptions

- .gitignore
- Groups/GroupFinder.ascx
- Groups/GroupFinder.ascx.cs
Add ability to hide attribute values from group finder search filters
- Hide Attribute Filter Values
---------
- Added ability to hide attribute values from group finder search filters.
---------
Venture
---------
---------
---------
No
> Group Finder Hide Attribute Filter Values

- Groups/GroupFinder.ascx.cs
Looked into issue #25 and found that it is by design that it only affects the campus filter, but is a misleading name and description on the block setting. It would take a lot of work to get all filters converted to single select due to using helper methods.
**Single Select Campus Filter**
---------
- Renamed block setting *Single Select Filters* to **Single Select Campus Filter**
---------
Warranty / reported in #25 
---------
---------
---------
No
> Single Select Filter Setting Renamed

- Groups/GroupFinder.ascx.cs
Check if they entered a postal code and it got a map coordinate before loading the default location... 
---------
* Fixed issue where using a default location would override any postal code entered by the user.
---------
LGO
---------
No
---------
---------
No
> Group Finder Default Location and Postal Code Bug

- CheckIn/AttendanceReport.ascx.cs
Makes the Default Check-In Group Type block setting optional.  By not forcing a Group Type in the block settings, this ensures intentionality when running the report.
When I initially wrote the block, I thought this value would be required at all times.  Now that the block is fully functioning, I was able to confirm a `string.Empty` value allows all dependent data bindings to reset and display blank.
---------
* Made the Default Check-In Group Type setting optional in the Attendance Report block.
---------
* CheckIn/AttendanceReport.ascx.cs
---------
No
> Don't require the block setting for Default Check-In Group Type.

- Import/sql/_rocks_kfs_spPersonImportWithAttendance_CSV.sql
Various updates to stored procedure to fix some bugs.
- You can now actually not have some columns defined, email/birthdate/connectionstatusid.
- Person matching on birthdate should actually work now.
- Added some status messages on how many group members and attendance records were created.
- Added some logic to test for empty ConnectionStatus and IsEmailActive if no email imported. 
- Adjusted for possible archived group members. They will be unarchived if re-imported.
---------
- You can now actually not have some columns defined, email/birthdate/connectionstatusid.
- Person matching on birthdate should actually work now.
- Added some status messages on how many group members and attendance records were created.
- Added some logic to test for empty ConnectionStatus and IsEmailActive if …
> Import Person with Attendance Updates

- Groups/GroupFinder.ascx
- Groups/GroupFinder.ascx.cs
Added custom schedules search support to group finder. You should now be able to find groups that meet every other Monday, 1st and 3rd Monday, and any other schedule that uses the BYDAY capability of the ical content.
Also brought in missing core changes to group finder. (Pending members, DefinedValuePicker instead of DDL and remove debug specific capabilities).
No, just enabled by default.
---------
- Custom Schedules are now supported in the Group Finder day of week filter.
- Bring in missing core changes to group finder. 
---------
LGO
---------
No, just works.
---------
---------
No, though I guess it could be a change of functionality if you didn't see custom schedules show up in search results before.
> Custom Schedule Support in GroupFinder

- Finance/PledgeEntryWithCampusContext.ascx.cs
- Finance/TransactionEntryWithSearch.ascx.cs
- Security/AccountEntry.ascx.cs
- WorkFlow/TransactionEntryWorkflowForm.ascx.cs
Update some obsolete methods through our blocks. Ignoring RegistrationEntry as that is old and deprecated itself. Need to still deprecate everything related to that.
---------
Updated a few blocks to now use the SystemCommunication instead of the SystemEmail and found a few more obsolete methods that needed an update as well.
---------
Warranty
---------
No
---------
- Finance/PledgeEntryWithCampusContext.ascx.cs
- Finance/TransactionEntryWithSearch.ascx.cs
- Security/AccountEntry.ascx.cs
- WorkFlow/TransactionEntryWorkflowForm.ascx.cs
---------
Yes/No, be sure to update your system communications text if there were any updates made since 10.2 when they migrated system emails to system communications.
> Update Obsolete Methods

- Webhooks/GetChannelFeeds.ashx
Pull in cache key changes from Core to our version of GetChannelFeeds webhook.
---------
* CacheDuration is now honored in our GetChannelFeeds webhook.
---------
OHC
---------
No
---------
Webhooks/GetChannelFeeds.ashx
---------
No
> GetChannel Feeds Webhook Update

- Groups/GroupFinder.ascx
- Groups/GroupFinder.ascx.cs
- Groups/GroupFinder_Readme.md
- Added Keyword search to search name or description of groups. (Had some weird viewstate issues with collapsible filters so it is a fully dynamic filter.)
- Fixed a minor issue with custom group schedules and Postal Code order for `Hidden on Initial Load` setting
- Keyword Label
- Display Keyword Search
---------
- Added Keyword search to search name or description of groups. 
- Fixed a minor issue with custom group schedules and Postal Code order for `Hidden on Initial Load` setting
---------
Kensington
---------
Added settings for Keyword:   
Stark view:   
---------
---------
No
> Group Finder Keyword Search

- Connection/ConnectionOpportunitySearch.ascx
- Connection/ConnectionOpportunitySearch.ascx.cs
This is an update to our copy of the Connection Opportunity Search block. It brings back in core capabilities with our existing dropdown list capabilities. In addition Kensington requested us to add the ability to search the summary and details of the opportunities.
(see screenshot)
- **Name Filter Label**
- **Search Summary and Details with Name Filter** - Determines if the 'Name Filter' also searches the summary and details of the opportunities.
---------
- Bring Connection Opportunity Search block up to v12.
- Added the ability to search summary and details of opportunities using the name filter.
---------
Kensington
---------
---------
- Connection/ConnectionOpportunitySearch.ascx
- Connection/ConnectionOpportunitySearch.ascx.cs
---------
No
> Connection Opportunity Search Block

- Groups/GroupFinder.ascx.cs
- Groups/GroupFinder_Readme.md
Added an additional setting to include Pending members in Over Capacity checking
**Overcapacity Groups include Pending**, When set to true, the Hide Overcapacity Groups setting also takes into account pending members.
---------
- Added an additional setting to include Pending members in Over Capacity checking
---------
Southbrook
---------
---------
---------
No
> Group Finder Pending Members in Group Capacity

- Eventbrite/EventbriteSettings.ascx.cs
Minor bug fixes to error display and using OrganizationId from settings.
---------
* Fixed issue with Eventbrite settings block displaying an incorrect error.
* Fixed issue where Organization may not be taken into account when loading new events.
---------
Warranty
---------
No
---------
Eventbrite/EventbriteSettings.ascx.cs
---------
Assembly update is required for this change due to new method.
> Eventbrite Bug Fixes

- CheckIn/Manager/Locations.ascx.cs
- Cms/PublicProfileEdit.ascx.cs
URL Encode label path before embedded pdf displays, due to possibility of special characters in names.
Fixed an issue with the Public Profile Edit block that exists in the core version, not updating phone numbers due to a missing "Unlisted" checkbox. (Removed requirement, though maybe I should have added that checkbox back?)
---------
- Fixed potential display issue with special characters in label names.
- Fixed issue with missing "Unlisted" checkbox on public profile edit block. 
---------
OHC 
---------
No
---------
- CheckIn/Manager/Locations.ascx.cs
- Cms/PublicProfileEdit.ascx.cs
---------
no
> Advanced Check-in Manager Tweak

- Communication/CommunicationListSubscribe.ascx
- Communication/CommunicationListSubscribe.ascx.cs
Adds a new block that allows for the display of communication lists grouped by category. Preserves default display if not configured to display by category. Based on the Communication List Subscribe Block
New Block based on the Communication List Subscribe block.
* Show List Categories
---------
* Added ability to show communication lists grouped by category.
---------
VCC
---------
---------
* Communication/CommunicationListSubscribe.ascx - Added dom
* Communication/CommunicationListSubscribe.ascx.cs - Added processing code behind
---------
No, new block.
> New Communication List Subscribe (with Categories)

- Communication/CommunicationListSubscribe.ascx.cs
Added setting that allows category to be either collapsed or expanded by default.
* Communication List Categories Default Expanded
---------
* Added ability for list categories to be expanded by default.
---------
Venture
---------
---------
* Communication/CommunicationListSubscribe.ascx.cs - Added module setting and removed unnecessary declaration
---------
None.
> Communication List Categories Expanded Block Setting

- Groups/GroupFinder.ascx
- Groups/GroupFinder.ascx.cs
Convert postal code to Textbox to support 10 digit zip code.
---------
Convert postal code to Textbox to support 10 digit zip code.
---------
OHC
---------
---------
---------
No
> Fix for group finder not supporting full 10 digit zip codes

- Groups/GroupFinder.ascx
- Groups/GroupFinder.ascx.cs
- Groups/GroupFinder_Readme.md
Bring in 12.5 group finder changes to KFS Version. Converted all attributes to new Const key format.
- **Group Type** changed to multi-select capable
- **Hide Overcapacity Groups**
- **Load Results on Initial Page Load**
- **Location Types**
- **Map Marker**
- **Min/Max Zoom Level**
- **Initial Zoom Level**
- **Marker Auto Scale Zoom Level/Amount**
- **Location Precision Level**
---------
- All 12.5 features brought into our KFS version.
- Multiple Group Type Support
- Location Types filter
- Additional Map options (Zoom levels and map marker customization)
---------
LGO
---------
---------
- Groups/GroupFinder_Readme.md
---------
No, it should still be compatible with previous versions, except the defined type may …
> 12.5 Group Finder Changes

- CheckIn/DisplayMessages.ascx
- CheckIn/DisplayMessages.ascx.cs
- Created Display Messages block to be able to load check-in state messages and log or display them to the user.
- Must be added where needed, such as Family Select page and Person Select (Family Check-in) page.
- _Detail Message_, By default the messages will come straight from the check-in state 'Messages' array. You can customize the message even further using lava, an array of 'Messages' is available to use what was provided from the current check-in state.
- _Type of Alert_, Select the type of alert box to show the messages in. ('Log only' found in ServiceLog table)
- _Process Messages on Postback Only_, Process messages on page load every time (false) or only on postback (true)?
- _Clear Messages on Display_ When the message gets displayed or logged, clear the …
> Check-in Display Messages Block

- StepsToCare/CareDashboard.ascx
- StepsToCare/CareDashboard.ascx.cs
Missed two phrases of "Convert To" changing to "Add"
---------
Missed two phrases of "Convert To" changing to "Add"
---------
RSC
---------
---------
---------
No
> Steps To Care - Missed "Convert To" updates.

- StepsToCare/CareDashboard.ascx.cs
- StepsToCare/CareEntry.ascx.cs
Add alignment to actions cell and add logging and a fix for geopoints that are null for care entry
_Verbose Logging_, added to Care Entry to help debug null reference errors.
---------
- Add a new setting for Verbose Logging in Care Entry.
- Fixed an issue when GeoPoints or HomeLocation are null for geofence workers.
---------
- RSC
---------
Before CSS fix:
After CSS Fix
---------
- StepsToCare/CareEntry.ascx.cs
---------
No
> Steps to Care Logging and GeoPoint fix

- StepsToCare/CareDashboard.ascx
- StepsToCare/CareDashboard.ascx.cs
- StepsToCare/CareEntry.ascx
- StepsToCare/CareEntry.ascx.cs
- StepsToCare/CareWorkers.ascx
- StepsToCare/CareWorkers.ascx.cs
Added capability to "Include Family" on care needs. Which will then create individual care needs for each family member and be assigned appropriately. With this new capability it will then display them on the dashboard underneath a + icon in a fashion similar to an accordion. If a Care worker is assigned to the parent and child need they will both show up at the top of the list in the default sort order. If a worker is only assigned to a "child" need and not the parent they will see the need in their assigned list outside of the accordion/collapsed view.
Care Entry:   
_Load Balanced Workers assignment type_, How should the auto assign worker load balancing work? Prioritize, it will prioritize the workers being assigned based on campus, category and any other parameters …
> Steps to Care Family/Sub Needs

- StepsToCare/CareEntry.ascx.cs
Add null check for age, in case the person doesn't have a birthdate, quite common scenario I missed.
---------
- Add null check for Age Precise which is being used in the round robin assignment
---------
RSC
---------
No
---------
StepsToCare/CareEntry.ascx.cs
---------
No
> Steps to Care - Null Birthdate check

- Groups/GroupFinder.ascx.cs
Bug fix in Group Finder for URL Param based filters and hiding values not working.
---------
- Fixed bug with URL Parameter filters not working in Group Finder. New Format: `filter_<attributeKey>_<attributeFieldTypeId>=<value>`
- Fixed bug with hiding attribute values no longer working.
---------
Warranty
---------
---------
---------
No
> Group Finder Bug Fix

- StepsToCare/CareDashboard.ascx
- StepsToCare/CareDashboard.ascx.cs
- StepsToCare/CareEntry.ascx
- StepsToCare/CareEntry.ascx.cs
- Ensure TargetPerson mode works properly and make some special considerations for such.
- Add new "Care Needs" page to Person Detail/Profile pages in Rock.
- Added new "CompleteNeeds" and "UpdateStatus" security permissions.
- **Complete Needs**, The roles and/or users that have access to Complete Needs.
- **Target Person Mode Include Family Members**, When running in Target Person mode/a Person Detail tab, should we include family member needs in the list? Default: false.
---------
- Ensure TargetPerson mode works properly and make some special considerations for such.
- Add new "Care Needs" page to Person Detail/Profile pages in Rock.
- Added new "CompleteNeeds" and "UpdateStatus" security permissions.
---------
RSC
---------
--------- …
> Steps to Care TargetPerson Mode

- Reporting/DynamicDataLava.ascx
- Reporting/DynamicDataLava.ascx.cs
This block gives you the ability to output lava into a Rock Grid will all its capabilities (format, filter, grid actions, etc.) You can use the standard ToJSON lava filter or create your own JSON object array.
- Show Lava Output for Debug Purposes
---------
- Gives you the ability to output lava into a Rock Grid with all its capabilities (format, filter, grid actions, etc.)
---------
LGO
---------
---------
- Reporting/DynamicDataLava.ascx
- Reporting/DynamicDataLava.ascx.cs
---------
No
> Dynamic Data Lava block

- CheckIn/PagerEntry.ascx.cs
- Add "Groups" setting to the Pager Entry block to restrict pager number entry displaying for only certain groups.
*Groups*, Select the check-in group(s) to utilize this pager entry capability. This capability will be displayed for all groups by default.
---------
- Add "Groups" setting to the Pager Entry block to restrict pager number entry displaying for only certain groups.
---------
RSC
---------
---------
CheckIn/PagerEntry.ascx.cs
---------
No, but a migration was added for proper installation. [RockAssemblies#](https://github.com/KingdomFirst/RockAssemblies/pull/80)
> Pager Entry Groups Setting

- Crm/PersonContactNotes.ascx
I am not sure why I was using `row-eq-height` class in this block, but it was unnecessary from what I could tell, so I removed it. Much better mobile view.
---------
- Added a fix for mobile view of Person Contact Notes.
---------
CBCNeenah
---------
Before:   
After:   
---------
Crm/PersonContactNotes.ascx
---------
No
> Person Contact Notes Mobile View

- CheckIn/PagerEntry.ascx.cs
Update to check-in pager entry. If you don't actually select a group during the check-in process, i.e. it gets auto selected, it will not be in the "Selected" result set, fix it so that is not required.
---------
- Fix Pager entry when groups are auto selected, still filter.
---------
RSC
---------
No
---------
CheckIn/PagerEntry.ascx.cs
---------
No
> Check-in Pager Entry Update

- StepsToCare/CareDashboard.ascx
- StepsToCare/CareDashboard.ascx.cs
- StepsToCare/CareEntry.ascx.cs
Add the capability to schedule future needs and display them. In order to do so all the assignment methods were moved to a common utility class instead of being located in the Care Entry Block.
Care Dashboard
- **Threshold of Days For Future Need**, The number of days the need has to be within before displaying on the dashboard.
Care Entry   
- **Threshold of Days before Assignment**, The number of days you can schedule a need in the future before a need will be assigned to workers.
---------
- Added capability to schedule future needs in Steps to Care.
---------
RSC
---------
Care Dashboard, "Include Future Needs"
Care Entry, new settings:
---------
- StepsToCare/CareEntry.ascx.cs
---------
Yes, new …
> Steps to Care Future Needs

- ShelbyFinancials/BatchesToJournal.ascx.cs
Fix for "Wait operation timed out" due to having too many integers in a NOT IN() SQL query when attempting to export multiple batches. Don't convert to list of Integers first so it can handle it with a SQL query instead. 
Previous Query (Not in could get 39,000+ integers in it): 
`SELECT ...
WHERE ... AND ( NOT ([Extent1].[Id] IN (...)))`
New Query:
`SELECT ...
WHERE ... AND ( NOT EXISTS (SELECT ...`
---------
- Fixed potential "Wait operation timed out" error when exporting multiple batches at the same time.
---------
College
---------
No
---------
ShelbyFinancials/BatchesToJournal.ascx.cs
---------
No
> Shelby Financials Exception with multiple batches selected

- Crm/PersonAttributeForms.ascx
- Crm/PersonAttributeForms.ascx.cs
- Crm/PersonAttributeForms_Readme.md
Added ability to run Person Attribute Forms Advanced in "Person Mode" that can be any person with guid, family members, or only logged in users. Also added a select a family member dropdown when not in only logged in users mode.
*Person Mode*, Person selection mode, should we allow family members, any person guid, or logged in user only.
*Display Family Member Picker*, Should we show the family member picker on the form? (Note: this will only display in Family Members or Anyone mode.)
---------
- Added ability to run Person Attribute Forms Advanced in "Person Mode" that can be any person with guid, family members, or only logged in users.
- Added an option to "Display a Family Member Picker" to work in tandem with this new mode.
---------
VWC
---------
---------
- …
> Person Attributes Advanced - Family Member Mode

- Communication/SmsConversations.ascx
- Communication/SmsConversations.ascx.cs
Brought in core SMS Conversations block and added a new checkbox to be able to filter down to just inbound text messages.
---------
- Added a new checkbox to be able to filter down to just inbound text messages.
---------
CBC Neenah
---------
---------
- Communication/SmsConversations.ascx
- Communication/SmsConversations.ascx.cs
---------
No
> SMS Conversations Modifications

- Groups/GroupFinder.ascx.cs
- StepsToCare/CareDashboard.ascx.cs
Fix for index out of range error when a worker is assigned to a child need but not the parent need and it goes into the follow up grid. Also snuck in a group finder fix for not always hiding attribute values depending on styles, especially in v14, need to mark as !important to hide.
---------
- Fixed an index out of range error when a need is in the follow up grid in a specific scenario.
---------
RSC/Warranty
---------
No
---------
---------
No
> Steps to Care - Index out of Range Fix

- StepsToCare/CareEntry.ascx.cs
Round robin assignment only (Care Workers) when "Workers only" is checked.
---------
- Fixed issue when "Workers Only" is selected only workers should be assigned through the round robin assignment, no small group leaders or "geofence"/deacon workers.
---------
RSC/Warranty
---------
No
---------
StepsToCare/CareEntry.ascx.cs
---------
No
> Steps to Care - Workers Only Fix

- Webhooks/SimpleTexting.ashx
Added webhook for Simple Texting. Supports delivery confirmation and processing incoming messages for sms pipeline, standard processing and sms conversations. Also supports media/mms attachments for v13+
---------
- Added webhook for SimpleTexting. Supports delivery confirmation and processing incoming messages for sms pipeline, standard processing and sms conversations. Also supports media/mms attachments for v13+
---------
VWC
---------
Internal to Rock
---------
Webhooks/SimpleTexting.ashx
---------
Requires the communication transport/component from https://github.com/KingdomFirst/RockAssemblies/pull/103
> Simple Texting Webhook

- Cms/PublicProfileEdit.ascx.cs
* Modified processing on line 1366 to be != adultGuid instead of == childGuid for supporting other family roles.
---------
* Modified processing on line 1366 to be != adultGuid instead of == childGuid for supporting other family roles.
---------
OHC
---------
No
---------
Cms/PublicProfileEdit.ascx.cs
---------
No
> Public Profile Edit for supporting other family roles

- Crm/PersonAttributeForms.ascx
- Crm/PersonAttributeForms.ascx.cs
Add support for conditional fields in Person Attribute Forms Advanced block. Due to the way it saves the fields to the database it currently only supports Attributes for conditions. This is not that different than Registration template conditional fields as the only supported person field was "Gender" there, but we cannot even support that in this block.
---------
- Added support for Conditional Fields/Form Field Filters on Person Attributes.
---------
OHC
---------
---------
- Crm/PersonAttributeForms.ascx
- Crm/PersonAttributeForms.ascx.cs
---------
No, there was one change to Guid's of fields, but steps were taken to make it backwards compatible when conditions are added.
> Person Attribute Forms Advanced Conditional Fields Support

- Crm/PersonAttributeForms.ascx.cs
Once deployed to client there was an issue found with attribute ids and registration form field ids conflicting. (See commits for bringing in core code and then the change I made to fix it)
---------
- Fixed conflict with attribute ids and registration form field ids with conditional fields.
---------
Warranty
---------
No
---------
Crm/PersonAttributeForms.ascx.cs
---------
No
> Person attributes form advanced Bug Fix

- Reporting/DynamicDataLava.ascx
- Reporting/DynamicDataLava.ascx.cs
Add support for Persisted Datasets in our Dynamic Data Lava block.
**_Persisted Dataset_**, If you would like to use a persisted dataset instead of a custom query select one here. Note this data is pre-rendered to be persisted, you will be limited to the grid filters for filter capability.
---------
- Added support for Persisted Datasets in our Dynamic Data Lava block.
---------
Warranty
---------
New Setting:   
When you select a persisted dataset it will hide other fields:   
---------
- Reporting/DynamicDataLava.ascx
- Reporting/DynamicDataLava.ascx.cs
---------
No
> Add support for Persisted Datasets in our Dynamic Data Lava block.

- Groups/GroupFinder.ascx.cs
Add try catch around smarty street method that can return a 500 error when an invalid postal code is provided.
---------
- Added protection for possible server error if an invalid postal code is provided.
---------
Venture/Warranty
---------
---------
---------
No
> Group Finder Postal Code Protection

- Groups/GroupFinder.ascx
- Groups/GroupFinder.ascx.cs
Added some new capabilities to Group Finder, including auto postback/auto reload search, show/hide full groups filter, require postal code and including attributes in keyword search.
- Auto filter enable
- Require Postal Code
- Attributes included in Keyword Search
---------
- Added additional capabilities including auto reload search, show/hide full groups filter, require postal code and including attributes in keyword search.
---------
North Coast
---------
Coming Soon
---------
---------
No
> Group finder enhancements

- StepsToCare/CareDashboard.ascx
- StepsToCare/CareDashboard.ascx.cs
Steps to care Popover Update, change from just name and photo to pull full contact information into popover instead.
---------
- Updated care requester name popover to include contact information instead of just the name and photo.
---------
RSC
---------
Before change:   
After Change:   
---------
---------
No
> Steps to Care Popover Update

- Crm/EditBusiness.ascx.cs
Replace deprecated/obsolete method with new GetNoPictureUrl method.
---------
Replace deprecated/obsolete method with new GetNoPictureUrl method.
---------
WCD
---------
No
---------
Crm/EditBusiness.ascx.cs
---------
The core rock change was a breaking change, though it should have just been marked obsolete without exception... The new method we are pointing to should be v14+ at least.
> Business Edit Update

- Import/sql/_rocks_kfs_spPersonImport_CSV.sql
Rock now requires GroupTypeId while inserting records into the GroupMember table. This change adds the necessary GroupTypeId field to the GroupMember portion of the _rocks_kfs_spPersonImport_CSV stored procedure.
---------
* Fixed bug causing error when using _rocks_kfs_spPersonImport_CSV stored procedure with KFS Spreadsheet Import block.
---------
Manna
---------
no
---------
* Import/sql/_rocks_kfs_spPersonImport_CSV.sql
---------
no
> Update Spreadsheet Import person import SQL for newer Rock versions

- Groups/GroupSelectedCommunication.ascx.cs
Gives the capability to specify what form input name to use, so you can use multiple copies of the blocks on the same page or customize the input name.
_Form Input Name_, The form input name, so you can use multiple copies of the block on the same page.
---------
- Added the capability to specify what form input name to use, so you can use multiple copies of the blocks on the same page or customize the input name.
---------
North Coast
---------
---------
Groups/GroupSelectedCommunication.ascx.cs
---------
No
> Group Selected Communication - Form Input Name

- Eventbrite/EventbriteSettings.ascx.cs
In Eventbrite settings block I went ahead and moved the databind behind isAuthenticated check.
---------
- Fixed an issue that could sometimes generate an exception on the settings block if the token was entered but invalid.
---------
Warranty
---------
Before:   
(or an exception if "Display Eventbrite Event Name" setting was set to "Yes")
After (no longer displays grid or attempts api calls):   
---------
Eventbrite/EventbriteSettings.ascx.cs
---------
No
> Eventbrite Bug Fix

- StepsToCare/CareDashboard.ascx.cs
- StepsToCare/CareEntry.ascx
- StepsToCare/CareEntry.ascx.cs
- Minor fix for Assigned Person grid not showing on edit.
- Added ability to be able to set who are the follow up workers on needs.
- _Follow Up Worker Assignment_, Enable the follow up worker to be assigned instead of just auto assigning the first worker added to need. Hide, existing behavior first worker gets assignment. Show, show a checkbox to assign follow up worker with first worker checked by default. Show and Assign All, show the checkbox and select all as default.
---------
- Minor fix for Assigned Person grid not showing on edit.
- Added ability to be able to set who are the follow up workers on needs.
---------
Warranty
---------
---------
- StepsToCare/CareEntry.ascx
- StepsToCare/CareEntry.ascx.cs
---------
No, though it …
> Steps to Care - Minor Fix and Editable Follow Up Workers

- RsvpGroups/Lava/RsvpGroupListSidebar.lava
- RsvpGroups/RsvpGroupRegistration.ascx.cs
Fixed old block to use newer v11+ methods.
---------
- Updated RSVP Group Registration to work on v11+
---------
KCC
---------
No
---------
- RsvpGroups/Lava/RsvpGroupListSidebar.lava
- RsvpGroups/RsvpGroupRegistration.ascx.cs
---------
No
> RSVP Group Reg Fix

- CheckIn/Manager/Locations.ascx.cs
- CheckIn/Manager/ReadMe.md
Rock added a new CheckInLabel class to Rock.Model in v [16.6](https://github.com/SparkDevNetwork/Rock/commit/f36a49f54ac9c73e063927b717634e1ce3d6099d#diff-ada733893782d8d503f6997750703c30c2c147d479025f288f011eb92c7d5cdc), causing an ambiguous reference with Rock.Checkin.CheckInLabel class when both namespaces are referenced. This change resolves the ambiguous reference.
---------
* Fixed CheckInLabel ambiguous reference error introduced with version 16.6 of Rock.
---------
Warranty
---------
No
---------
* CheckIn/Manager/Locations.ascx.cs
---------
No
> Advanced Checkin Monitor - Fixed ambiguous reference bug in Locations block caused by Rock v16.6 changes

- Groups/GroupFinder.ascx
- Groups/GroupFinder.ascx.cs
- The new Group/Sign Up Opportunities were not sorted by anything, so we have added a default sort order and added support for proximity sort now. 
- Updated distances to now report `9999` miles if there is no location attached to the group. This will now force Groups without a location to the end of the list, where before they would be removed from the result completely when sorting by distance and entering an address or postal code.
- Fixed a typo in the setting panel.
---------
- The new Group/Sign Up Opportunities were not sorted by anything, so we have added a default sort order and added support for proximity sort now. 
- Updated distances to now report `9999` miles if there is no location attached to the group. This will now force Groups without a location to the end of the list, …
> Group Finder Update for Sorting

- Groups/GroupFinder.ascx.cs
- Added a fix for the map when a mapItem does not have a valid Point it should be ignored. Reported by Michael Allen.
- Ended up refactoring the map generator code to be able to load from either Group Opportunities or not, that way it can filter out some that are further filtered by the location schedule.
- Fixed a presenting issue with the Group Opportunities showing _all_ opportunities when a day of week was selected if any of those opportunities fell on that day of the week.
---------
- Fixed Null reference when using anything other than "Precise" for Location Precision Level setting. 
- Fixed an issue with some group opportunities still showing up on the map even though their occurrence was in the past.
- Added additional `Opportunities` merge field to map marker lava when using "Add …
> Advanced Group Finder Bug Fixes

- StepsToCare/CareDashboard.ascx
- StepsToCare/CareDashboard.ascx.cs
- StepsToCare/CareEntry.ascx.cs
- StepsToCare/CareNoteTemplates.ascx.cs
- StepsToCare/CareWorkers.ascx.cs
Steps to Care Assign to Group(s) changes in Care Entry and minor bug fix. Goes along with https://github.com/KingdomFirst/RockAssemblies/pull/160
**Additional changes:**    
- Fixed Care touches not always counting appropriately.
- Added new setting to hide add button based on edit permission
- Added follow up touch hours setting to dashboard
- Added support for Alert and Private settings with "quick notes" to match note timeline input.
- Fixed attribute support for Care Entry, Care Dashboard, Care Workers and Note Templates (this includes loading attribute values, attribute filters, grid columns and overall lots of bugs with them).
---------
- New Qualifiers added for Assigned Person grid.
- Fixed Care touches not always counting appropriately.
- Added new setting to hide add button …
> Steps to Care Assign to Group(s) changes and minor bug fix

- Groups/GroupAttendanceMulti.ascx
- Groups/GroupAttendanceMulti.ascx.cs
- Added LastName buttons to jump down in long lists.
- Added ability to add an attendee to specific occurrence for a specific group.
- Added new setting to combine or not combine attendance in multiple groups.
- Added attended count and support for lava logic to hide the card.
_Display LastName Buttons_, Display a row of buttons with the first letter of LastName buttons. Default: Yes
_Allow Adding Person_, Should block support adding new people as attendees?
_Combine Group Attendance_, Should the block combine multiple group attendance to each person?
---------
- Added LastName buttons to jump down in long lists.
- Added ability to add an attendee to specific occurrence for a specific group.
- Added new setting to combine or not combine attendance in multiple groups.
- …
> Multi Group Attendance Updates

- Groups/GroupFinder.ascx.cs
- Fixed block generating an exception when using a single-select day of week filter
- Also found that Auto Filter was not working for single-select day of week and the time filter.
---------
- Fixed block generating an exception when using a single-select day of week filter
- Fixed Auto Filter for single-select day of week and the time filter.
---------
Warranty
---------
No
---------
---------
No
> Group Finder Bugs with "Single Select" Day of Week filter

- Groups/GroupAttendanceMulti.ascx.cs
Using improper GroupLocation.Id instead of GroupLocation.LocationId for AttendanceOccurrence
---------
- Fixed issue where wrong location would get attached to occurrence.
---------
Warranty
---------
No
---------
Groups/GroupAttendanceMulti.ascx.cs
---------
No
> Multi Group Attendance Bug

- ShelbyFinancials/BatchToJournal.ascx.cs
- ShelbyFinancials/BatchesToJournal.ascx.cs
Added block setting to both Batch To Journal and Batches To Journal blocks to control whether projects are added to credit lines only, debit lines only, or both.
* Project Handling Mode
---------
* Added ability to control whether projects are added to credit lines only, debit lines only, or debit an credit lines in both Batch To Journal and Batches To Journal blocks.
---------
Hill Country Bible Church
---------
Batch To Journal Block Settings  
Batches To Journal Block Settings  
Example - Debit And Credit Lines  
Example - Debit Lines Only  
Example - Credit Lines Only  
---------
* ShelbyFinancials/BatchToJournal.ascx.cs
* ShelbyFinancials/BatchesToJournal.ascx.cs
---------
dependency on https://github.com/KingdomFirst/RockAssemblies/pull/167
> Shelby Financials Batch To Journal and Batches To Journal

- Eventbrite/Sync.ashx
Add attendee.updated back to webhook support, due to possible intermediate mode between "Info Requested" and actually entering attendee information info would only be added with this webhook call.
---------
- Fixed webhook not firing when attendee info was entered as a separate part of the registration.
---------
Warranty
---------
No
---------
Eventbrite/Sync.ashx
---------
Documentation needs to be updated to reflect that you need to choose `attendee.updated` as part of the webhook setup.
> Eventbrite Webhook Update

- Cms/ProfileBioEdit.ascx.cs
- Communication/CommunicationListSubscribe.ascx
- Communication/CommunicationListSubscribe.ascx.cs
- Fixed two bugs with new Edit Profile block, delete new family member was not actually working and save changes button was still showing even if you had no family members.
- Updated Communication List Subscribe with a new CSS Class setting to control display a bit better.
_List Repeater CSS Class_, CSS Class to use on the category list repeater.
---------
- Fixed two bugs with new Edit Profile block, delete new family member was not actually working and save changes button was still showing even if you had no family members.
- Updated Communication List Subscribe with a new CSS Class setting to control display a bit better.
---------
VWC
---------
No more save button when no family members:   
Ability to have multiple columns using CSS instead of each one forced to a …
> Bug Fixes for Edit Profile and Communication List Subscribe

- FinancialEdge/BatchesToJournal.ascx.cs
- ShelbyFinancials/BatchesToJournal.ascx.cs
Minor bug fix for Shelby Financials and Financial Edge "Batches To Journal" blocks. Date Exported would not save a properly formatted value to the attribute.
---------
Minor bug fix for Shelby Financials and Financial Edge "Batches To Journal" blocks.
---------
Warranty
---------
No
---------
- ShelbyFinancials/BatchesToJournal.ascx.cs
- FinancialEdge/BatchesToJournal.ascx.cs
---------
No
> Financial Edge and Shelby Financials minor bug fix
